dist: trusty
sudo: false

notifications:
  email: false

language: node_js

git:
  depth: 1

os:
  - osx
  - linux

env:
  matrix:
    - CODE_VERSION="1.19.0"

cache:
  apt: true
  yarn: true
  bundler: true
  timeout: 604800
  directories:
    - node_modules

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

after_success:
  - if [[ ! -z "${CODECOV_TOKEN}" ]]; then bash <(curl -s https://codecov.io/bash); fi;
