dist: trusty
sudo: false

notifications:
  email: false

language: node_js

node_js:
  - 7.4 # Sort with the version bundled in supported vscode.

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  # - npm install
  # - npm run vscode:prepublish

script:
  - true
